defaults:
  - _self_
  - dataset: main/modus

model:
  name: "meta-llama/Llama-3.2-3B-Instruct"
  type: "hf"
  skills:
    - name: "modus_ponens"
      checkpoint_path: null
      length: 20
      replace_str: "modus ponens"

training:
  dataset_path: ${dataset.dataset_path}
  col_prompt: ${dataset.col_prompt}
  col_completion: ${dataset.col_completion}
  skill_save_strategy: "epoch"
  skill_save_steps: 500

trainer_args:
  num_train_epochs: 10
  learning_rate: 5e-3
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 2
  logging_strategy: "steps"
  eval_strategy: "steps"
  eval_steps: 10
  logging_steps: 2
  eval_on_start: false
  do_eval: true
  lr_scheduler_type: "linear"
  logging_dir: "./logs"
  gradient_checkpointing: true

output:
  dir: null

wandb:
  enabled: true
  tags: ["train_skill", "modus_ponens"]
  notes: ""
  project: "skill-neologisms-skillmix"
