pretrained:
  checkpoint: "antoninbrthn/skill-neologisms-qwen2.5-digitseq-base"

model:
  name: "Qwen/Qwen2.5-0.5B"

skill:
  name: "PREFIX"
  length: 20
  description: "prompt_tuning_prefix"
  init_method: "from_pretrain_skills"
  checkpoint_path: null

dataset:
  skill_op: "[SHIFT_RIGHT]"
  test_op: "[ADD]"
  num_samples: 100000
  val_dataset_size: 1000
  test_dataset_size: 200
  seq_length: 9
  seq_len_min: 2
  reject_len: [5, 7, 9]
  min_ops: 1
  max_ops: 3

wandb:
  enabled: true
  project: "skill-neologisms"
  tags: ["baseline", "prompt-tuning"]

training:
  max_length: 512
  max_new_tokens: 10

trainer_args:
  num_train_epochs: 3
  learning_rate: 5e-3
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  logging_strategy: "steps"
  eval_strategy: "steps"
  warmup_steps: 500
  save_steps: 500
  eval_steps: 500
  logging_steps: 100
  do_eval: true
  logging_dir: "./logs"
  eval_on_start: true

output:
  save_dir: "baseline_prompt_tuning"
  save_history: true
